defaultContentLanguage: en
enableRobotsTXT: true
enableGitInfo: true
frontmatter:
  lastmod: ["lastmod", ":git", "date", "publishDate"]
author:
  name: Sivert V. Sæther
  email: gmail@sivert.pw
copyright: GPL-3
taxonomies:
  category: categories
  series: series
  tag: tags