---
kind: pipeline
type: docker
name: build and publish

steps:
- name: build and publish
  image: registry.42069.no/build/hugo
  environment:
    KEY:
      from_secret: key
  commands:
    - mkdir ~/.ssh && echo "$KEY" > ~/.ssh/id_rsa && chmod 600 -R ~/.ssh
    - hugo -e prod --printI18nWarnings --printPathWarnings --printUnusedTemplates --templateMetricsHints
    - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
    - git clone --branch gh-pages git@github.com:Ghost-Zephyr/Ghost-Zephyr.github.io.git github
    - cp -r public/* github/
    - cd github/ && git add -A && git commit -m "Drone CI!~ [$(git rev-parse --short HEAD)](https://github.com/Ghost-Zephyr/Ghost-Zephyr.github.io/commit/$(git rev-parse HEAD))" && git push

image_pull_secrets:
- registry

