---
kind: pipeline
type: docker
name: build and publish

steps:
- name: build
  image: build/hugo
  settings:
    registry: registry.42069.no
    username: siv
    password:
      from_secret: registry
  commands:
  - hugo -e prod --printI18nWarnings --printPathWarnings --printUnusedTemplates --templateMetricsHints

