---
kind: pipeline
type: docker
name: build and publish

steps:
- name: build
  image: registry.42069.no/build/hugo
  commands:
  - hugo -e prod --printI18nWarnings --printPathWarnings --printUnusedTemplates --templateMetricsHints

image_pull_secrets:
- dockerconfig
