---
kind: pipeline
type: docker
name: build and publish

steps:
- name: build
  image: plugins/hugo
  settings:
    hugo_version: 0.110.0
    validate: true

- name: publish
  image: plugins/gh-pages
  settings:
    pages_directory: public/
    username: Ghost-Zephyr
    password: 
      from_secret: password

