---
kind: pipeline
type: docker
name: build and publish

steps:
- name: build
  image: mbentley/hugo
  commands:
  - hugo -e prod --printI18nWarnings --printPathWarnings --printUnusedTemplates --templateMetricsHints

